### PR TITLE
[OPS-7442] update core to 8.9.14

### PR DESCRIPTION
**Pull request by lazysoundsystem**
https://humanitarian.atlassian.net/browse/OPS-7442

and updates ubuntu travis version to 'bionic'.

### CODE REVIEW

**Review by orakili — COMMENTED** [review]
@lazysoundsystem Any reason for the bump to php 7.4 (.travis.yml and symphony.lock)? The SLT site is still running with PHP 7.3: https://github.com/UN-OCHA/slt8-site/blob/cee11a9273232619614c21bdab07e48030b0c54a/docker/Dockerfile#L34 so for consistency it might be better to also use that in travis as well.

**Comment by lazysoundsystem** [comment]
Thanks for the review - composer updated to a later version as specified in the composer.json, and I updated the rest to match that. I've now fixed the php version in composer.json in https://github.com/UN-OCHA/slt8-site/pull/24, so closing this.

**Comment by lazysoundsystem** [comment]
As the tests failed on the other branch, requiring more specificity in the php version in travis, re-opening this to try it just with the php version in travis.yml reduced to 7.3.

**Comment by lazysoundsystem** [comment]
Leaving this as is, with the travis requirement returned to php7.3.

The other approach failed as my local version of php is at 7.4. If it's worth it, I can reduce that and re-open that PR for 7.3. Not sure if this needs more discussion.

**Comment by orakili** [comment]
Thanks.

**Pull request merged**
