### PR TITLE
[SLT-45] update to Drupal 9

### PR DESCRIPTION
**Pull request by lazysoundsystem**
https://humanitarian.atlassian.net/browse/SLT-45

This was meant to replace https://github.com/UN-OCHA/slt8-site/pull/37 as I assumed that would have conflicts with the updated dev branch, but it appears not to. So it's very nearly the same, with an updated social_auth_hid module and a bit of tidying up.

Still, closing the other in favour of this one.

### CODE REVIEW

**Review by cafuego — APPROVED** [review]
All in order as far as I can tell.

**Review by orakili — CHANGES_REQUESTED** [review]
The update to the `symfony.lock` file seems to not have been committed.

Also I would suggest to add some of the changes from https://github.com/UN-OCHA/slt8-site/pull/37/commits/ca14bae81f431c62e7138e1cbe0ffada807f89df, notably the update of the scripts/composer/ScriptHandler.php to add `removeUnnecessaryFiles` method with the corresponding post-install/update commands in the composer.json file.

Without it, after running composer install, the repo is messy with unwanted files like `config/bootstrap.php` etc. (you can test with `rm -rf vendot` followed by `composer install`).

**Comment by lazysoundsystem** [comment]
This now includes https://github.com/UN-OCHA/slt8-site/pull/39 - bumping to php8.0

**Comment by lazysoundsystem** [comment]
Back to you @orakili for another review - this time without the Migrate modules and bumped to php8.

**Pull request merged**
